### ISSUE TITLE
Fails to show result

### ISSUE THREAD

**Issue by 7rebor** [tischi/fiji-plugin-imageRegistration#2]
Hi,

I let the plugin run in the background for some of my data (a two-channel XYZ stack doing XY transform along Z), and it fails to complete (see error at bottom of post). I'm using up-to-date FIJI with EMBL-CBA and BigStitcher update sites. The plugin definitely does something prior to failing, it might just be failing to show the result, I get stuff like the following read out to the console: 

```
[INFO] translations 10.962735162577562
[INFO] translations -5.737945623698579
[INFO] x-corr 0.4866060862660478
[INFO] ### TransformationFinderTranslationPhaseCorrelation
nPortions for copy:8
nPortions for copy:8
nPortions for copy:8
nPortions for copy:8
PCM
expand
cross 1143
sort
done
```

Error when failing to complete:

```
    ### Result
    org.scijava.module.MethodCallException: Error executing method: de.embl.cba.registration.gui.ImageRegistrationPlugin#computeRegistration
    	at org.scijava.module.MethodRef.execute(MethodRef.java:73)
    	at org.scijava.module.AbstractModuleItem.callback(AbstractModuleItem.java:229)
    	at org.scijava.widget.DefaultWidgetModel.callback(DefaultWidgetModel.java:187)
    	at org.scijava.ui.swing.widget.SwingButtonWidget$1.actionPerformed(SwingButtonWidget.java:83)
    	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    	at java.awt.Component.processMouseEvent(Component.java:6535)
    	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    	at java.awt.Component.processEvent(Component.java:6300)
    	at java.awt.Container.processEvent(Container.java:2236)
    	at java.awt.Component.dispatchEventImpl(Component.java:4891)
    	at java.awt.Container.dispatchEventImpl(Container.java:2294)
    	at java.awt.Component.dispatchEvent(Component.java:4713)
    	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    	at java.awt.Container.dispatchEventImpl(Container.java:2280)
    	at java.awt.Window.dispatchEventImpl(Window.java:2750)
    	at java.awt.Component.dispatchEvent(Component.java:4713)
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    	at java.awt.EventQueue.access$500(EventQueue.java:97)
    	at java.awt.EventQueue$3.run(EventQueue.java:709)
    	at java.awt.EventQueue$3.run(EventQueue.java:703)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    	at java.awt.EventQueue$4.run(EventQueue.java:731)
    	at java.awt.EventQueue$4.run(EventQueue.java:729)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
    Caused by: java.lang.reflect.InvocationTargetException
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at org.scijava.module.MethodRef.execute(MethodRef.java:69)
    	... 39 more
    Caused by: java.lang.NullPointerException
    	at java.util.Arrays.stream(Arrays.java:5095)
    	at de.embl.cba.registration.transformationfinders.TransformationFinderRotationTranslationPhaseCorrelation$Result.toString(TransformationFinderRotationTranslationPhaseCorrelation.java:199)
    	at de.embl.cba.registration.transformationfinders.TransformationFinderRotationTranslationPhaseCorrelation.findTransform(TransformationFinderRotationTranslationPhaseCorrelation.java:95)
    	at de.embl.cba.registration.ImageRegistration.run(ImageRegistration.java:231)
    	at de.embl.cba.registration.gui.ImageRegistrationPlugin.registrationThread(ImageRegistrationPlugin.java:247)
    	at de.embl.cba.registration.gui.ImageRegistrationPlugin.access$000(ImageRegistrationPlugin.java:48)
    	at de.embl.cba.registration.gui.ImageRegistrationPlugin$1.run(ImageRegistrationPlugin.java:281)
    	at java.lang.Thread.run(Thread.java:745)
    	at de.embl.cba.registration.gui.ImageRegistrationPlugin.computeRegistration(ImageRegistrationPlugin.java:285)
    	... 44 more
```

**Comment by tischi** [comment]
Happy new year @7rebor!

I changed tons of stuff! Could you please test if it works better after updating your Fiji and thereby installing the latest version?

**Comment by 7rebor** [comment]
Ok, updated and tested, and it definitely runs this time! I will create a new issue about my problems with it.
